import type { Config } from "tailwindcss";

// Design tokens sourced verbatim from docs/stitch_splitkid/kindred_path/DESIGN.md
// (the "Kindred Path" design system behind the Stitch mockups). Keep this in
// sync with that file — it's the source of truth referenced in the project brief.
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#f8faf4",
        "surface-dim": "#d9dbd5",
        "surface-bright": "#f8faf4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4ee",
        "surface-container": "#edefe9",
        "surface-container-high": "#e7e9e3",
        "surface-container-highest": "#e1e3dd",
        "on-surface": "#191c19",
        "on-surface-variant": "#414941",
        "inverse-surface": "#2e312e",
        "inverse-on-surface": "#eff1ec",
        outline: "#717970",
        "outline-variant": "#c0c9be",
        "surface-tint": "#326943",
        primary: "#326943",
        "on-primary": "#ffffff",
        "primary-container": "#6da67a",
        "on-primary-container": "#003a1a",
        "inverse-primary": "#99d4a5",
        secondary: "#6a5c4e",
        "on-secondary": "#ffffff",
        "secondary-container": "#f3dfce",
        "on-secondary-container": "#706254",
        tertiary: "#46617b",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#809cb8",
        "on-tertiary-container": "#16334b",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#b4f1bf",
        "primary-fixed-dim": "#99d4a5",
        "on-primary-fixed": "#00210c",
        "on-primary-fixed-variant": "#18512d",
        "secondary-fixed": "#f3dfce",
        "secondary-fixed-dim": "#d6c3b3",
        "on-secondary-fixed": "#231a0f",
        "on-secondary-fixed-variant": "#514538",
        "tertiary-fixed": "#cde5ff",
        "tertiary-fixed-dim": "#adc9e7",
        "on-tertiary-fixed": "#001d32",
        "on-tertiary-fixed-variant": "#2e4962",
        background: "#f8faf4",
        "on-background": "#191c19",
        "surface-variant": "#e1e3dd",
        "growth-green": "#4F7758",
        "journal-peach": "#F9E4D4",
        "alert-soft-red": "#E6A5A5",
        "surface-beige": "#FDFBF7",
        "text-main": "#2D312E",
      },
      fontFamily: {
        "display-lg": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "body-lg": ["Nunito Sans"],
        "body-md": ["Nunito Sans"],
      },
      fontSize: {
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        "container-padding": "24px",
        "element-gap": "16px",
        "section-margin": "32px",
        "grid-gutter": "16px",
      },
    },
  },
  plugins: [],
} satisfies Config;
